/* @flow */

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE'

export const LOGOUT = 'LOGOUT'

// art

export const UPLOAD_ART = 'UPLOAD_ART'
export const UPLOAD_ART_SUCCESS = 'UPLOAD_ART_SUCCESS'
export const UPLOAD_ART_FAILURE = 'UPLOAD_ART_FAILURE'

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE'


// mission


export const GET_TODAY_MISSION = 'GET_TODAY_MISSION'
export const GET_TODAY_MISSION_SUCCESS = 'GET_TODAY_MISSION_SUCCESS'
export const GET_TODAY_MISSION_FAILURE = 'GET_TODAY_MISSION_FAILURE'

export const GET_NOTIFICATION_MISSION = 'GET_NOTIFICATION_MISSION'
export const GET_NOTIFICATION_MISSION_SUCCESS = 'GET_NOTIFICATION_MISSION_SUCCESS'
export const GET_NOTIFICATION_MISSION_FAILURE = 'GET_NOTIFICATION_MISSION_FAILURE'

export const SET_MISSION_TO_SHOW_TYPE = 'SET_MISSION_TO_SHOW_TYPE'

export const UPLOAD_DONE_MISSION = 'UPLOAD_DONE_MISSION'
export const UPLOAD_DONE_MISSION_FAILURE = 'UPLOAD_DONE_MISSION_FAILURE'
export const UPLOAD_DONE_MISSION_SUCCESS = 'UPLOAD_DONE_MISSION_SUCCESS'

export const REQUEST_NOTIFICATION = 'REQUEST_NOTIFICATION'
export const REQUEST_NOTIFICATION_SUCCESS = 'REQUEST_NOTIFICATION_SUCCESS'
export const REQUEST_NOTIFICATION_FAILURE = 'REQUEST_NOTIFICATION_FAILURE'








// control flow
export const SET_CURRENT_VIEWPAGE = 'SET_CURRENT_VIEWPAGE'
export const SET_MY_PAGE_DROP_DOWN_LIST_SHOW_STATE = 'SET_MY_PAGE_DROP_DOWN_LIST_SHOW_STATE'
