export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE'

export const UPLOAD_DONE_MISSION = 'UPLOAD_DONE_MISSION'
export const UPLOAD_DONE_MISSION_FAILURE = 'UPLOAD_DONE_MISSION_FAILURE'
export const UPLOAD_DONE_MISSION_SUCCESS = 'UPLOAD_DONE_MISSION_SUCCESS'

export const UPLOAD_ART = 'UPLOAD_ART'
export const UPLOAD_ART_SUCCESS = 'UPLOAD_ART_SUCCESS'
export const UPLOAD_ART_FAILURE = 'UPLOAD_ART_FAILURE'

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE'

export const GET_TODAY_MISSION = 'GET_TODAY_MISSION'




export const SET_CURRENT_VIEWPAGE = 'SET_CURRENT_VIEWPAGE'
